[tool.bumpversion]
current_version = "2.3.4"
commit = true
tag = true
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)(.(?P<patch>\\d+))?"
serialize = [
    "{major}.{minor}.{patch}",
    "{major}.{minor}"
]

[[tool.bumpversion.files]]
filename = "VERSION"
