name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            flatpak \
            flatpak-builder \
            xvfb

      - name: Cache flatpak user installation
        uses: actions/cache@v3
        with:
          path: ~/.local/share/flatpak
          key: flatpak-user-${{ runner.arch }}

      - name: Cache flatpak-builder state directory
        uses: actions/cache@v3
        with:
          path: .flatpak-builder
          key: flatpak-builder-${{ runner.arch }}

      - name: Add Flathub repository
        run: |
          flatpak remote-add --user --if-not-exists flathub \
            https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Build flatpak
        # The build needs to be run under Xvfb (or some other virtual
        # display server) so that Gdk initialization succeeds in the
        # tests.
        run: |
          xvfb-run --auto-servernum -- \
            flatpak-builder --user --install-deps-from=flathub --repo _repo _flatpak \
            build-aux/flatpak/org.learningequality.Kolibri.Devel.json

      - name: Create flatpak bundle
        run: |
          flatpak build-bundle _repo org.learningequality.Kolibri.Devel.flatpak org.learningequality.Kolibri.Devel

      - name: Upload flatpak bundle
        uses: actions/upload-artifact@v3
        with:
          name: flatpak
          path: org.learningequality.Kolibri.Devel.flatpak
